"""empty message

Revision ID: 1f2fa860b36d
Revises: 
Create Date: 2019-12-14 15:18:38.476324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2fa860b36d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('dept', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('taskinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_charge', sa.Integer(), nullable=True),
    sa.Column('user_pub', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('isFinish', sa.Boolean(), nullable=True),
    sa.Column('pb_content', sa.Text(), nullable=True),
    sa.Column('pb_time', sa.DateTime(), nullable=True),
    sa.Column('ddl', sa.DateTime(), nullable=True),
    sa.Column('sb_content', sa.Text(), nullable=True),
    sa.Column('sd_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_charge'], ['userinfo.id'], ),
    sa.ForeignKeyConstraint(['user_pub'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['taskinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    op.drop_table('taskinfo')
    op.drop_table('userinfo')
    # ### end Alembic commands ###
